# Generated by Django 5.1.4 on 2024-12-15 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="guests",
            field=models.ManyToManyField(
                blank=True, related_name="guest_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
